language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

matrix:
  allow_failures:
  - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - composer install

script:
  - find . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n1 php -lf
  - phpcs --standard=PSR1,PSR2 --extensions=php --ignore="/ext_scripts/*,/ext_inc/*,/vendor/*" . || true # Allow failures for now
  - bin/phpunit
